//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadComics.resources.credentialsSettings {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CredentialsSettingsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CredentialsSettingsStrings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DownloadComics.resources.credentialsSettings.CredentialsSettingsStrings", typeof(CredentialsSettingsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Device Name.
        /// </summary>
        internal static string CredentialSettings_Device_Name_Label {
            get {
                return ResourceManager.GetString("CredentialSettings_Device_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email and/or password and/or device name are wrong.
        /// </summary>
        internal static string CredentialsSettings_Connection_Error {
            get {
                return ResourceManager.GetString("CredentialsSettings_Connection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection Failed.
        /// </summary>
        internal static string CredentialsSettings_Connection_Info_Label_Off {
            get {
                return ResourceManager.GetString("CredentialsSettings_Connection_Info_Label_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection Seccessful.
        /// </summary>
        internal static string CredentialsSettings_Connection_Info_Label_On {
            get {
                return ResourceManager.GetString("CredentialsSettings_Connection_Info_Label_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection Test.
        /// </summary>
        internal static string CredentialsSettings_Connection_Test_Button {
            get {
                return ResourceManager.GetString("CredentialsSettings_Connection_Test_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string CredentialsSettings_Password_Label {
            get {
                return ResourceManager.GetString("CredentialsSettings_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string CredentialsSettings_Save_Button {
            get {
                return ResourceManager.GetString("CredentialsSettings_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Credentials Settings.
        /// </summary>
        internal static string CredentialsSettings_Title {
            get {
                return ResourceManager.GetString("CredentialsSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Credentials has been saved successfully .
        /// </summary>
        internal static string Msg_Settings_Saved {
            get {
                return ResourceManager.GetString("Msg_Settings_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        internal static string Msg_Settings_Saved_Title {
            get {
                return ResourceManager.GetString("Msg_Settings_Saved_Title", resourceCulture);
            }
        }
    }
}
