//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadComics.resources.main {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainStrings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DownloadComics.resources.main.MainStrings", typeof(MainStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup.
        /// </summary>
        public static string Main_Backup_Menu_Item {
            get {
                return ResourceManager.GetString("Main_Backup_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Source.
        /// </summary>
        public static string Main_Change_Source_Button {
            get {
                return ResourceManager.GetString("Main_Change_Source_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Comics.
        /// </summary>
        public static string Main_Clear_Comics_Button {
            get {
                return ResourceManager.GetString("Main_Clear_Comics_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Previous Session.
        /// </summary>
        public static string Main_Clear_Session_MenuItem {
            get {
                return ResourceManager.GetString("Main_Clear_Session_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Settings.
        /// </summary>
        public static string Main_Export_Settings_Menu_Item {
            get {
                return ResourceManager.GetString("Main_Export_Settings_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Json Files.
        /// </summary>
        public static string Main_File_Dialog_Json {
            get {
                return ResourceManager.GetString("Main_File_Dialog_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import links.
        /// </summary>
        public static string Main_Import_Menu_Item {
            get {
                return ResourceManager.GetString("Main_Import_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Settings.
        /// </summary>
        public static string Main_Import_Settings_Menu_Item {
            get {
                return ResourceManager.GetString("Main_Import_Settings_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import of.
        /// </summary>
        public static string Main_Import_Title {
            get {
                return ResourceManager.GetString("Main_Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string Main_Language_Menu_Item {
            get {
                return ResourceManager.GetString("Main_Language_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Jdownloader Settings.
        /// </summary>
        public static string Main_Open_Jdownloader_Settings_Menu_Item {
            get {
                return ResourceManager.GetString("Main_Open_Jdownloader_Settings_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Settings.
        /// </summary>
        public static string Main_Open_Settings_Menu_Item {
            get {
                return ResourceManager.GetString("Main_Open_Settings_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restore Backup.
        /// </summary>
        public static string Main_Restore_Backup_Menu_Item {
            get {
                return ResourceManager.GetString("Main_Restore_Backup_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Language.
        /// </summary>
        public static string Main_Select_Lang_Menu_Item {
            get {
                return ResourceManager.GetString("Main_Select_Lang_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Main_Settings_Menu_Item {
            get {
                return ResourceManager.GetString("Main_Settings_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Submit.
        /// </summary>
        public static string Main_Submit_Menu_Item {
            get {
                return ResourceManager.GetString("Main_Submit_Menu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comics Manager.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unselect.
        /// </summary>
        public static string Main_Unselect_Button {
            get {
                return ResourceManager.GetString("Main_Unselect_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string Main_Update_Button {
            get {
                return ResourceManager.GetString("Main_Update_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Msg_Error_Tile {
            get {
                return ResourceManager.GetString("Msg_Error_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selectionned file not found.
        /// </summary>
        public static string Msg_File_Not_Found {
            get {
                return ResourceManager.GetString("Msg_File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to import the file.
        /// </summary>
        public static string Msg_Import_Error {
            get {
                return ResourceManager.GetString("Msg_Import_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings imported successfully.
        /// </summary>
        public static string Msg_Import_Settings {
            get {
                return ResourceManager.GetString("Msg_Import_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        public static string Msg_Import_Settings_Title {
            get {
                return ResourceManager.GetString("Msg_Import_Settings_Title", resourceCulture);
            }
        }
    }
}
